import Head from "next/head"
import { AiOutlineCompass,AiFillLinkedin, AiFillGithub, AiTwotoneMail, AiTwotoneExclamationCircle} from "react-icons/ai"
import Image from "next/image"
import styles from '../styles/index.module.css'; // Import your component-specific styles


export default function Home() {
  return (
<div>
  <Head>
    <title>Aster Wu - Full Stack developer</title>
    <meta name='description' content='Generated by cre'></meta>
  <link rel='icon' href ='/favicon.ico' />
  </Head>
  <main className="bg-white px-10">
    <section className="bg-pink-200 h-screen">
      <nav className="py-10 mb-12 flex justify-between">
        <h1 className="text-xl"></h1>

        <ul className="flex items-center">
          <li><AiOutlineCompass className="cursor-pointer text-2xl"/></li>
          <li><a className="bg-gradient-to-r from-purple-500 to-fuchsia-600 text-white px-4 py-2 border-none rounded-md ml-8" href="#">Resume</a></li>
        </ul>
      </nav>
      <div className="text-center p-10">
        <h2 className="text-5xl py-2 text-purple-800 font-medium" >Aster Wu</h2>
        <h3 className="text-2xl py-2 text-purple-900">Full-Stack Web Developer.</h3>
        <div className={`${styles.clipNotch} text-md py-5 leading-8 text-purple-950 border-2 p-6 border-fuchsia-700 clip-notch`}>
        <p>
          Some realized their passion is coding before 18, and I realized it after recieving degrees in economy and business, and working differnet jobs.           Luckily, I'm never afraid of learning new things, and have graduated from Lighthouse Labs Web Development Bootcamp after 12 weeks of intense, immersive studying. 
        </p>
        <p>
          Life is a series of never-ending challenges, and now I feel ready for my new challenge as web developer. 
        </p>
        </div>
      </div>
      <div className="text-5xl flex justify-center gap-16">
        <AiFillLinkedin/>
        <AiFillGithub/>
        <AiTwotoneMail/>
        <div className="">

        </div>
      </div>
    </section>
    <div>
      <h3></h3>
    </div>
  </main>
</div>
  )
}
